/**
 * @project FabriHub - Front
 * @file src/global/modules/icons/moduleIcons.tsx
 * @description Traduce la clave `icon` de catalogs_modules a un ícono Tabler
 */

import type { ComponentType } from "react";
import {
  IconAdjustments,
  IconApps,
  IconArrowsExchange,
  IconBarcode,
  IconBuilding,
  IconBuildingFactory2,
  IconBuildingWarehouse,
  IconCalendarStats,
  IconCategory,
  IconClipboardList,
  IconCurrencyDollar,
  IconFileCertificate,
  IconFileDollar,
  IconFileInvoice,
  IconFlask,
  IconHistory,
  IconIdBadge2,
  IconLayoutDashboard,
  IconListDetails,
  IconListNumbers,
  IconMicroscope,
  IconPackage,
  IconPackageExport,
  IconPackages,
  IconPercentage,
  IconReceipt,
  IconReceiptTax,
  IconRosetteDiscountCheck,
  IconRoute,
  IconScale,
  IconSettings,
  IconShieldLock,
  IconShoppingCart,
  IconStack2,
  IconTags,
  IconTimeline,
  IconTool,
  IconTruck,
  IconTruckDelivery,
  IconUserDollar,
  IconUsers,
  IconUsersGroup,
  IconUserStar,
  type IconProps
} from "@tabler/icons-react";

const ICONS: Record<string, ComponentType<IconProps>> = {
  adjustments: IconAdjustments,
  apps: IconApps,
  "arrows-exchange": IconArrowsExchange,
  barcode: IconBarcode,
  building: IconBuilding,
  "building-factory-2": IconBuildingFactory2,
  "building-warehouse": IconBuildingWarehouse,
  "calendar-stats": IconCalendarStats,
  category: IconCategory,
  "clipboard-list": IconClipboardList,
  "currency-dollar": IconCurrencyDollar,
  "file-certificate": IconFileCertificate,
  "file-dollar": IconFileDollar,
  "file-invoice": IconFileInvoice,
  flask: IconFlask,
  history: IconHistory,
  "id-badge-2": IconIdBadge2,
  "layout-dashboard": IconLayoutDashboard,
  "list-details": IconListDetails,
  "list-numbers": IconListNumbers,
  microscope: IconMicroscope,
  package: IconPackage,
  "package-export": IconPackageExport,
  packages: IconPackages,
  percentage: IconPercentage,
  receipt: IconReceipt,
  "receipt-tax": IconReceiptTax,
  "rosette-discount-check": IconRosetteDiscountCheck,
  route: IconRoute,
  scale: IconScale,
  settings: IconSettings,
  "shield-lock": IconShieldLock,
  "shopping-cart": IconShoppingCart,
  "stack-2": IconStack2,
  tags: IconTags,
  timeline: IconTimeline,
  tool: IconTool,
  truck: IconTruck,
  "truck-delivery": IconTruckDelivery,
  "user-dollar": IconUserDollar,
  users: IconUsers,
  "users-group": IconUsersGroup,
  "user-star": IconUserStar
};

export function ModuleIcon({ icon, ...props }: { icon: string | null } & Omit<IconProps, "name">) {
  const Icon = (icon && ICONS[icon]) || IconApps;
  return <Icon stroke={1.6} {...props} />;
}
